/*
 * Vincent Houle
 * 
 * script d'insertion de données manquantes
 * 
 */
USE tp_livre;

INSERT INTO arme (nom) VALUES
	("poignard"),
	("lance"),
	("masse d'armes"),
	("sabre"),
	("marteau de guerre"),
	("épée une main"),
	("hache"),
	("épée deux mains"),
	("baton"),
	("glaive"),
	("rien")
;

INSERT INTO discipline (nom, description) VALUES
	("canouflage","Cette technique permet au Seigneur Kaï de se fondre dans le paysage. A la campagne, il peut se cacher parmi les arbres et les rochers et se rendre de cette façon invisible à l'ennemi même s'il passe tout près de lui. Dans une ville, cette discipline donnera à celui qui l'utilise la faculté d'avoir l'air d'un habitant du cru, tant par l'apparence que par l'accent ou la langue employée. On peut ainsi trouver un abri où se cacher en toute sécurité."),
	("chasse", "Cette discipline donne au Seigneur Kaï l'assurance qu'il ne mourra jamais de faim même s'il se trouve dans un environnement hostile. Il aura toujours la possibilité de chasser pour se procurer de la nourriture, sauf dans les déserts et les autres régions arides. Cette technique permet également de se déplacer sans bruit en pistant une proie. Si vous choisissez cette discipline, inscrivez sur votre Feuille d'Aventure : Chasse ; vous êtes dispensé de Repas chaque fois qu'il est obligatoire de manger (voir plus loin le paragraphe Nourriture)."),
	("sixème sens", "Grâce à cette technique, le Seigneur Kaï devine les dangers imminents qui le menacent. Ce Sixième Sens peut également lui révéler les intentions véritables d'un inconnu ou la nature d'un objet étrange rencontré au cours d'une aventure. Si vous choisissez cette discipline, inscrivez : Sixième Sens sur votre Feuille d'Aventure."),
	("orientation","Chaque fois qu'il se trouvera dans l'obligation de décider quelle direction il doit prendre, le Seigneur Kaï fera toujours le bon choix grâce à cette technique. Il saura ainsi quel chemin il convient d'emprunter dans une forêt et il pourra également, dans une ville, découvrir l'endroit où sont cachés une personne ou un objet. Par ailleurs, il saura interpréter chaque trace de pas, chaque empreinte qui pourrait lui permettre de remonter une piste. Si vous choisissez cette discipline, inscrivez : Orientation sur votre Feuille d'Aventure."),
	("guérison","Cette discipline donne la faculté de récupérer des points d'ENDURANCE perdus lors d'un combat. Si vous maîtrisez cette technique, vous pourrez ajouter 1 point d'ENDURANCE à votre total à chaque fois qu'il vous sera possible d'aller d'un bout à l'autre d'un paragraphe sans avoir à combattre un ennemi. (Vous n'aurez droit d'utiliser cette technique de la Guérison que lorsque vos points d'ENDURANCE seront tombés au-dessous de votre total initial. Rappelez-vous que vos points d'ENDURANCE ne peuvent en aucun cas excéder votre total de départ). Si vous choisissez cette discipline, inscrivez sur votre Feuille d'Aventure : Guérison ; 1 point d'ENDURANCE pour chaque paragraphe parcouru sans combat."),
	("poigard", "En entrant au Monastère Kaï, chaque élève a la possibilité d'être initié au maniement d'une arme. Si vous choisissez d'avoir la Maîtrise d'une arme, utilisez la Table de Hasard à la manière indiquée plus haut pour obtenir un chiffre qui correspondra, dans la liste ci-dessous, à l'arme dont on vous aura enseigné le maniement. Vous aurez dès lors la parfaite Maîtrise de cette arme et chaque fois que vous combattrez avec elle, vous aurez droit à 2 points d'HABILETÉ supplémentaires."),
	("lance", "En entrant au Monastère Kaï, chaque élève a la possibilité d'être initié au maniement d'une arme. Si vous choisissez d'avoir la Maîtrise d'une arme, utilisez la Table de Hasard à la manière indiquée plus haut pour obtenir un chiffre qui correspondra, dans la liste ci-dessous, à l'arme dont on vous aura enseigné le maniement. Vous aurez dès lors la parfaite Maîtrise de cette arme et chaque fois que vous combattrez avec elle, vous aurez droit à 2 points d'HABILETÉ supplémentaires."),
	("masse d'armes", "En entrant au Monastère Kaï, chaque élève a la possibilité d'être initié au maniement d'une arme. Si vous choisissez d'avoir la Maîtrise d'une arme, utilisez la Table de Hasard à la manière indiquée plus haut pour obtenir un chiffre qui correspondra, dans la liste ci-dessous, à l'arme dont on vous aura enseigné le maniement. Vous aurez dès lors la parfaite Maîtrise de cette arme et chaque fois que vous combattrez avec elle, vous aurez droit à 2 points d'HABILETÉ supplémentaires."),
	("sabre", "En entrant au Monastère Kaï, chaque élève a la possibilité d'être initié au maniement d'une arme. Si vous choisissez d'avoir la Maîtrise d'une arme, utilisez la Table de Hasard à la manière indiquée plus haut pour obtenir un chiffre qui correspondra, dans la liste ci-dessous, à l'arme dont on vous aura enseigné le maniement. Vous aurez dès lors la parfaite Maîtrise de cette arme et chaque fois que vous combattrez avec elle, vous aurez droit à 2 points d'HABILETÉ supplémentaires."),
	("marteau de guerre", "En entrant au Monastère Kaï, chaque élève a la possibilité d'être initié au maniement d'une arme. Si vous choisissez d'avoir la Maîtrise d'une arme, utilisez la Table de Hasard à la manière indiquée plus haut pour obtenir un chiffre qui correspondra, dans la liste ci-dessous, à l'arme dont on vous aura enseigné le maniement. Vous aurez dès lors la parfaite Maîtrise de cette arme et chaque fois que vous combattrez avec elle, vous aurez droit à 2 points d'HABILETÉ supplémentaires."),
	("épée une main", "En entrant au Monastère Kaï, chaque élève a la possibilité d'être initié au maniement d'une arme. Si vous choisissez d'avoir la Maîtrise d'une arme, utilisez la Table de Hasard à la manière indiquée plus haut pour obtenir un chiffre qui correspondra, dans la liste ci-dessous, à l'arme dont on vous aura enseigné le maniement. Vous aurez dès lors la parfaite Maîtrise de cette arme et chaque fois que vous combattrez avec elle, vous aurez droit à 2 points d'HABILETÉ supplémentaires."),
	("hache", "En entrant au Monastère Kaï, chaque élève a la possibilité d'être initié au maniement d'une arme. Si vous choisissez d'avoir la Maîtrise d'une arme, utilisez la Table de Hasard à la manière indiquée plus haut pour obtenir un chiffre qui correspondra, dans la liste ci-dessous, à l'arme dont on vous aura enseigné le maniement. Vous aurez dès lors la parfaite Maîtrise de cette arme et chaque fois que vous combattrez avec elle, vous aurez droit à 2 points d'HABILETÉ supplémentaires."),
	("épée deux main", "En entrant au Monastère Kaï, chaque élève a la possibilité d'être initié au maniement d'une arme. Si vous choisissez d'avoir la Maîtrise d'une arme, utilisez la Table de Hasard à la manière indiquée plus haut pour obtenir un chiffre qui correspondra, dans la liste ci-dessous, à l'arme dont on vous aura enseigné le maniement. Vous aurez dès lors la parfaite Maîtrise de cette arme et chaque fois que vous combattrez avec elle, vous aurez droit à 2 points d'HABILETÉ supplémentaires."),
	("baton", "En entrant au Monastère Kaï, chaque élève a la possibilité d'être initié au maniement d'une arme. Si vous choisissez d'avoir la Maîtrise d'une arme, utilisez la Table de Hasard à la manière indiquée plus haut pour obtenir un chiffre qui correspondra, dans la liste ci-dessous, à l'arme dont on vous aura enseigné le maniement. Vous aurez dès lors la parfaite Maîtrise de cette arme et chaque fois que vous combattrez avec elle, vous aurez droit à 2 points d'HABILETÉ supplémentaires."),
	("glaive", "En entrant au Monastère Kaï, chaque élève a la possibilité d'être initié au maniement d'une arme. Si vous choisissez d'avoir la Maîtrise d'une arme, utilisez la Table de Hasard à la manière indiquée plus haut pour obtenir un chiffre qui correspondra, dans la liste ci-dessous, à l'arme dont on vous aura enseigné le maniement. Vous aurez dès lors la parfaite Maîtrise de cette arme et chaque fois que vous combattrez avec elle, vous aurez droit à 2 points d'HABILETÉ supplémentaires."),
	("boulier psychique", "Les Maîtres des Ténèbres et les nombreuses créatures malfaisantes qui leur obéissent ont la faculté de vous porter atteinte en faisant usage de leur force psychique. La technique du Bouclier psychique vous permet cependant de ne pas perdre de points d'ENDURANCE lorsque vous vous trouvez soumis à une telle agression. Si vous choisissez cette discipline, inscrivez sur votre Feuille d'Aventure : Bouclier psychique ; pas de perte d'ENDURANCE en cas d'agression mentale."),
	("puissance psychique", "Cette technique permet au Seigneur Kaï d'attaquer un ennemi en se servant de la force de son esprit : on peut l'utiliser en même temps qu'une arme de combat habituelle et l'on dispose alors de 2 points supplémentaires d'HABILETÉ. Cette puissance psychique, cependant, n'est pas forcément efficace avec toutes les créatures: il se peut que certaines d'entre elles y soient insensibles. Si le cas se présente, vous en serez averti au cours de votre mission. Si vous choisissez cette discipline, inscrivez sur votre Feuille d'Aventure : Puissance psychique ; 2 points d'HABILETÉ supplémentaires."),
	("communication animale", "Grâce à cette technique, un Seigneur Kaï peut communiquer avec certains animaux et deviner les intentions de certains autres. Si vous choisissez cette discipline, inscrivez : Communication Animale sur votre Feuille d'Aventure."),
	("maîtrise psychique de la matière", "C'est une technique qui donne à un Seigneur Kaï la faculté de déplacer de petits objets par le simple pouvoir de sa concentration mentale. Si vous choisissez cette discipline, inscrivez : Maîtrise Psychique de la Matière sur votre Feuille d'Aventure. Si vous remplissez avec succès la mission qui vous est assignée dans ce premier livre de la série du Loup Solitaire, vous aurez le droit d'ajouter une Discipline Kaï supplémentaire à celles que vous possédez déjà. Lorsque vous vous lancerez dans la nouvelle aventure que vous propose le prochain volume de la série (intitulé La Traversée Infernale), vous pourrez ainsi faire usage de six disciplines Kaï (les cinq premières étant acquises une bonne fois pour toutes), de même que des Objets Spéciaux que vous aurez décidé de conserver au cours de votre première mission. Sachez en effet que, de livre en livre, votre expérience grandira chaque fois que vous aurez accompli une mission : vous pourrez, de cette façon, espérer atteindre un jour la complète maîtrise de l'art et de la science des Moines Kaï.")
;

INSERT INTO livre (titre, auteur) VALUES
	("Les Maîtres des Ténèbres", "Joe Dever")
;



